global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.31.20.60:9100']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['172.31.20.60:9187']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['172.31.20.60:9121']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

rule_files:
  - "alert-rules/*.yml"
