apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header 'Access-Control-Allow-Origin' '*' always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
      add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Authorization' always;

      if ($request_method = OPTIONS) {
          add_header 'Access-Control-Allow-Origin' '*';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
          add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Authorization';
          add_header 'Content-Length' 0;
          add_header 'Content-Type' text/plain;
          return 204;
      }
spec:
  rules:
    - host: movie.local
      http:
        paths:
          - path: /movie(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: movieapi
                port:
                  number: 8000
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8082
