---
- name: Deploy application to EC2 with Docker and Docker Compose
  hosts: web
  become: yes

  vars:
    app_dir: /opt/myapp
    project_dir: "{{ playbook_dir }}/.."  # local project path

  tasks:
  
    - name: Remove old Docker repository definitions (to avoid Signed-By conflicts)
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove old Docker key if present
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent
      when: ansible_os_family == "Debian"

    - name: Ensure apt packages are up to date (Debian/Ubuntu)
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Debian"

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"


    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure ubuntu user is in the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy init SQL file to EC2
      copy:
        src: "{{ project_dir }}/databases/init/init.sql"
        dest: /tmp/init.sql

    - name: Ensure filebeat directory exists
      file:
        path: /opt/myapp/filebeat
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy filebeat.yml file to EC2
      copy:
        src: "{{ project_dir }}/filebeat/filebeat.yml"
        dest: "{{ app_dir }}/filebeat/filebeat.yml"

    - name: Copy .env file to EC2
      copy:
        src: "{{ project_dir }}/.env"
        dest: "{{ app_dir }}/.env"
        mode: '0600'

    - name: Stop running containers
      become: false
      shell: docker compose -f docker-compose.yml down --remove-orphans
      args:
        chdir: "{{ project_dir }}"
      environment:
        DOCKER_HOST: "ssh://ec2-docker"
      delegate_to: localhost

    - name: Start application with Docker Compose over SSH
      become: false
      shell: |
        docker compose -f docker-compose.yml pull &&
        docker compose -f docker-compose.yml up -d
      args:
        chdir: "{{ project_dir }}"
      environment:
        DOCKER_HOST: "ssh://ec2-docker" 
      delegate_to: localhost

      
    - name: Copy SQL file from EC2 host into container
      command: docker cp /tmp/init.sql postgres:/tmp/init.sql


    - name: Initialize Postgres table
      command: docker exec -i postgres psql -U postgres -d movies_db -f /tmp/init.sql



